name: Bug report
description: Send a bug WinUEFI has that needs to be fixed
title: "[BUG] <title>"
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: |
        Thank you for filling out a bug that WinUEFI has! It helps me make the application better. Please be as detailed as possible so that i may consider and review the bug easier.

  - type: textarea
    id: bug-and-suggestion-relation
    attributes:
      label: Is your bug related to a suggestion?
      description: Please give some context for this request. Why do you want it to be fixed?
