name: Restart Services
on:
  workflow_dispatch:

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    
    steps:
      - name: Restart App Server release
        if: ${{ contains(github.ref_name, 'release') || github.ref == 'refs/heads/release' }}
        run: |
          echo "Release Branch"
          echo "${{ github.ref_name }} - ${{ contains(github.ref_name, 'release') }}"
          echo ${{ github.ref }}
      
      - name: Restart App Server development
        if: ${{ contains(github.ref_name, 'release') == false || github.ref != 'refs/heads/release' }}
        run: |
          echo "Not Release Branch"
          echo "${{ github.ref_name }} - ${{ contains(github.ref_name, 'release') }}"
          echo ${{ github.ref }}
